#!/usr/bin/env python

import argparse
import xarray as xr
from pyautoQC.metadataQC import compare_dataset_coords

parser = argparse.ArgumentParser(description='check coordinates of file \
                                              against reference file')

parser.add_argument("file_to_test", type=str,
                    help="file to test")

parser.add_argument("file_ref", type=str,
                    help="reference file")

args = parser.parse_args()

ds_test = xr.open_dataset(args.file_to_test)
ds_ref = xr.open_dataset(args.file_ref)

compare_dataset_coords(ds_test, ds_ref)
