#!/usr/bin/env python

import argparse
import xarray as xr
from pyautoQC.metadataQC import compare_dataset_dims
import warnings


parser = argparse.ArgumentParser(description='check dimensions of file \
                                              against reference file')

parser.add_argument("file_to_test", type=str,
                    help="file to test")

parser.add_argument("file_ref", type=str,
                    help="reference file")

parser.add_argument("--Wall", help='show warnings')

args = parser.parse_args()

if not args.Wall:
    warnings.filterwarnings("ignore")

ds_test = xr.open_dataset(args.file_to_test)
ds_ref = xr.open_dataset(args.file_ref)

compare_dataset_dims(ds_test, ds_ref)
