#!/usr/bin/env python

import argparse
import xarray as xr
from pyautoQC.metadataQC import compare_dataset_dims
from pyautoQC.metadataQC import compare_dataset_coords
import warnings


parser = argparse.ArgumentParser(description='check dimensions of all files \
                                              against reference file')

parser.add_argument('-l', '--listfiles', nargs='+', required=True,
                    help="files to test")

parser.add_argument('-r', '--ref', type=str, required=True,
                    help="reference file")

parser.add_argument("--Wall", help='show warnings')

args = parser.parse_args()

if not args.Wall:
    warnings.filterwarnings("ignore")

ds_ref = xr.open_dataset(args.ref)

for file_to_test in args.listfiles:
    print('checking file ', file_to_test, 'against', args.ref)
    ds_test = xr.open_dataset(file_to_test)
    check, message = compare_dataset_dims(ds_test, ds_ref)
    if not check:
        print(message)
    check, message = compare_dataset_coords(ds_test, ds_ref)
    if not check:
        print(message)
